version: '2'
services:
  redis:
    image: "redis:5"

  database:
    image: postgres
    volumes:
    - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ekster
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simple
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    image: "pstuifzand/ekster:alpine"
    working_dir: /opt/microsub
    links:
      - redis:redis
    volumes:
      - ./data:/opt/microsub
      - ./templates:/app/templates
      - ./eksterd:/app/eksterd
    entrypoint: /app/eksterd
    command: -auth=false -port 80 -templates /app/templates
    ports:
      - 8089:80
    environment:
      - "FEEDBIN_USER="
      - "FEEDBIN_PASS="
      - "EKSTER_BASEURL=http://localhost:8089/"
      - "EKSTER_TEMPLATES=/app/templates"

volumes:
    database-data:
